# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]

jobs:

  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Prepare
        id: prepare
        run: |
            TAG=${GITHUB_REF##*/}
            echo ::set-output name=tag_name::${TAG} 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login do docker.io
        run: docker login -u odidev -p ${{ secrets.DOCKER_TOKEN }}
      - name: build and publish image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
             odidev/cfs-base:${{ steps.prepare.outputs.tag_name }}
             odidev/cfs-base:latest

  ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check gofmt
        run: |
          find . -type f -name "*.go" | grep -v 'vendor' |grep -v 'depends'| xargs gofmt -l > gofmt_results.txt
          cat gofmt_results.txt
          if [ "$(cat gofmt_results.txt|wc -l)" -gt 0  ]; then exit 1; fi
      - name: Build and run CI tests
        run: |
          docker/run_docker.sh -t
          docker/run_docker.sh -l
      - name: Pack docker_data
        if: ${{ always() }}
        run: pushd docker && sudo tar --exclude='docker_data/datanode*/disk' --exclude='docker_data/disk' -czvf docker_data.tar.gz docker_data
      - name: Upload docker_data.tar.gz
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: docker_data
          path: docker/docker_data.tar.gz
          retention-days: 7
          
